apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlan-cni-installer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: vlan-cni
  template:
    metadata:
      labels:
        app: vlan-cni
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: installer
        image: vlan-cni:latest
        command: ["/install.sh"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni-bin
          mountPath: /opt/cni/bin
        - name: cni-conf
          mountPath: /etc/cni/net.d
      volumes:
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: cni-conf
        hostPath:
          path: /etc/cni/net.d