apiVersion: v1
kind: Pod
metadata:
  name: socni-example
  annotations:
    k8s.v1.cni.cncf.io/networks: kube-system/socni-vlan
spec:
  containers:
  - name: example
    image: busybox
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m" 