apiVersion: v1
kind: ServiceAccount
metadata:
  name: socni
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: socni
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: socni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: socni
subjects:
- kind: ServiceAccount
  name: socni
  namespace: kube-system 