apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vlan-cni-plugin
  namespace: kube-system
  labels:
    app: vlan-cni-plugin
spec:
  selector:
    matchLabels:
      app: vlan-cni-plugin
  template:
    metadata:
      labels:
        app: vlan-cni-plugin
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: vlan-cni-plugin
        image: vlan-cni:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni-bin
          mountPath: /opt/cni/bin
        - name: cni-net-d
          mountPath: /etc/cni/net.d
        - name: host-run
          mountPath: /var/run/vlan-cni
        - name: config-volume
          mountPath: /etc/vlan-cni/config
      volumes:
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: cni-net-d
        hostPath:
          path: /etc/cni/net.d
      - name: host-run
        hostPath:
          path: /var/run/vlan-cni
          type: DirectoryOrCreate
      - name: config-volume
        configMap:
          name: vlan-cni-config