apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-namespace.yaml
- 01-storage.yaml
- 02-daemon.yaml
- 03-network.yaml
- 04-monitoring.yaml
- 05-backup.yaml
- 06-restore-job.yaml
- 07-policy-configmap.yaml
- 08-policy-init.yaml

commonLabels:
  app.kubernetes.io/part-of: aranya
  app.kubernetes.io/managed-by: kustomize 