apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aranya-daemon
spec:
  template:
    spec:
      containers:
      - name: aranya-daemon
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m" 